# 1. Conexión a la Base de Datos Distribuida (MongoDB)
spring.data.mongodb.uri=mongodb://localhost:27017/smartgym

# 2. Conexión a Apache Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=backend-procesamiento
spring.kafka.consumer.auto-offset-reset=earliest

# 3. Variables para conectarnos a Mosquitto (MQTT)
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=spring-boot-backend
mqtt.topic.telemetria=smartgym/telemetria
mqtt.topic.accesos=smartgym/accesos